apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-results-service
  labels:
    app: results-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: results-service
  template:
    metadata:
      labels:
        app: results-service
    spec:
      containers:
        - name: results-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
