apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-monitor-service
  labels:
    app: monitor-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: monitor-service
  template:
    metadata:
      labels:
        app: monitor-service
    spec:
      containers:
        - name: monitor-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
